-- File: sevensegdec_nexys.vhd
-- Generated by MyHDL 0.11.52
-- Date:    Tue Oct  6 04:17:22 2026 UTC


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity sevensegdec_nexys is
    port (
        bcd: in unsigned(3 downto 0);
        sseg: out unsigned(6 downto 0);
        bcdled: out unsigned(3 downto 0);
        ssanodes: out unsigned(7 downto 0);
        invert: in std_logic
    );
end entity sevensegdec_nexys;


architecture MyHDL of sevensegdec_nexys is



signal sevensegdec0_ssegout: unsigned(6 downto 0);

begin




sevensegdec0_logic: process (bcd) is
begin
    case to_integer(bcd) is
        when 0 => sevensegdec0_ssegout <= "1111110";
        when 1 => sevensegdec0_ssegout <= "0110000";
        when 2 => sevensegdec0_ssegout <= "1101101";
        when 3 => sevensegdec0_ssegout <= "1111001";
        when 4 => sevensegdec0_ssegout <= "0110011";
        when 5 => sevensegdec0_ssegout <= "1011011";
        when 6 => sevensegdec0_ssegout <= "1011111";
        when 7 => sevensegdec0_ssegout <= "1110000";
        when 8 => sevensegdec0_ssegout <= "1111111";
        when 9 => sevensegdec0_ssegout <= "1111011";
        when 10 => sevensegdec0_ssegout <= "1001001";
        when 11 => sevensegdec0_ssegout <= "0110110";
        when 12 => sevensegdec0_ssegout <= "0011101";
        when 13 => sevensegdec0_ssegout <= "1100011";
        when 14 => sevensegdec0_ssegout <= "0011100";
        when others => sevensegdec0_ssegout <= "1001000";
    end case;
end process sevensegdec0_logic;

sevensegdec0_invertproc: process (sevensegdec0_ssegout, invert) is
begin
    if bool(invert) then
        sseg <= (not sevensegdec0_ssegout);
    else
        sseg <= sevensegdec0_ssegout;
    end if;
end process sevensegdec0_invertproc;


bcdled <= bcd;
ssanodes <= to_unsigned(254, 8);

end architecture MyHDL;
